In [26]:
 grid = [[5,3,0,0,7,0,0,0,0,],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]
    

In [27]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [28]:
import numpy as np
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [29]:
def possible(y,x,n):
        global grid
        for i in range(0,9):
            if grid[y][i] == n :
                return False
        for i in range(0,9):
            if grid[i][x] == n:
                return False
        x0 = (x//3)*3
        y0 = (y//3)*3
        for i in range(0,3):
            for j in range(0,3):
                if grid[y0+i][x0+j] ==n:
                    return False
            return True

In [30]:
#possible(4,4,3)
possible(8,2,9)

False

In [31]:
possible(4,4,5)

True

In [32]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        #print(np.matrix(grid))
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input("More?")

In [33]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More?


Above is a brute force approach, can we attempt a more human like solution?

In [44]:
def printgrid(gr = grid):
    """
    print the board
    :param grid: the global grid
    :return: printed formatted grid
    """
    for i in range(0,9):
        if i % 3 == 0 and i != 0:
            print("- - - - - - - - - -")
        for j in range(0,9):
            if j % 3 ==0 and j != 0:
                print(" | ", end ="")
            if j ==8:
                print(gr[i][j], end= "\n")
            else:
                print(str(gr[i][j]), end = "")
    
printgrid()
#print(np.matrix(grid)) #same grid as above

530 | 070 | 000
600 | 195 | 000
098 | 000 | 060
- - - - - - - - - -
800 | 060 | 003
400 | 803 | 001
700 | 020 | 006
- - - - - - - - - -
060 | 000 | 280
000 | 419 | 005
000 | 080 | 079


In [68]:
# use possible from above
def human_solve1(): #loop through numbers and find unique spots
    global grid
    for y in range(0,9):
        for x in range(0,9):
            for n in range(1,10):
                #can i place a number here based off of rows and col with n?
                if grid[y][x] == 0 and possible(y,x,n): #if empty
                    x0 = (x//3)*3
                    y0 = (y//3)*3 #square coordinates
                    
                    if len(grid[y0].count(n) == 1 and )
                    print(x0)
                    print(y0)
                    #print(n)
                    
    

In [93]:

grid[0:3]
type(grid)
#human_solve1()

list

In [101]:
a = np.matrix(grid)
a[0,0]


#a.tolist()

5